### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by r-barnes** [njsmith/colorspacious#1]
I wish the docs were just a little more complete on this and would show how to simulate the various forms of colour blindness on an image.

**Comment by njsmith** [comment]
I wrote a much more complete tutorial and reference manual this weekend -- see if it does what you need?

https://colorspacious.readthedocs.org/en/latest/

**Comment by njsmith** [comment]
(Closing this for now b/c there's no todo item for me in it ATM, but feedback is very much welcome)
