### ISSUE TITLE
Issue with conversion from sRGB255 to JCh and back

### ISSUE THREAD

**Issue by mycarta** [njsmith/colorspacious#2]
I get some odd result when converting a png image of some data with Jet colormap:
![in](https://cloud.githubusercontent.com/assets/7424763/13910536/5e1e7b02-eee9-11e5-8fd9-a05275299a68.png)

from sRGB255 to JCh and back:
![srgb255-jch-srgb255](https://cloud.githubusercontent.com/assets/7424763/13910539/6bb68aa2-eee9-11e5-9787-23fd16bb1949.png)

The result looks instead normal when converting the input to 0-1 range and converting from sRGB1 to JCh and back:
![srgb1-jch-srgb1](https://cloud.githubusercontent.com/assets/7424763/13910544/8524c1c0-eee9-11e5-8896-f62cf41fbab3.png)

I've loaded a complete example at this GitHub location: 
https://github.com/mycarta/PerceptualColormaps/blob/master/test_color_conversions_rgb-2-JCh-2-rgb_and_rgb-2-LCh-2-rgb.ipynb

**Comment by njsmith** [comment]
I think the problem is that `matplotlib` expects float arrays to be [0, 1] and integer arrays to be [0, 255], and converting to and from JCh gives you a float array on [0, 255]. Try doing `np.round(rgb_J).astype(int)` and see if that helps? or just sticking with sRGB1 should also work :-)

**Comment by njsmith** [comment]
(Note that you can reproduce the problem by just doing `img = img.astype(float); plt.imshow(img)` without using colorspacious at all.)

**Comment by mycarta** [comment]
Thanks for the tips.
Unfortunately using `rgb_JJ = np.around(rgb_J).astype(int) ` did not change the outcome. And similarly, when I tried `img = img.astype(float); plt.imshow(img)` (which as you suggests, reproduces the problem), followed by `img = np.round(img).astype(int); plt.imshow(img)` I also do not get back my original image.

I think I will stick with sRGB1.
};-)

**Comment by njsmith** [comment]
Maybe it's `.astype(np.uint8)` that matplotlib is looking for? In any case, sounds like you've found a solution and there's nothing for colorspacious to do :-)
