### ISSUE TITLE
please include LICENSE.txt file in the PyPI tarball release

### ISSUE THREAD

**Issue by sandrotosi** [njsmith/colorspacious#7]
Hello,
in the source code is referred the file LICENSE.txt to look at the license, but that's not included in the pypi released tarball: could you please include it in the next upload?

thanks!

**Comment by njsmith** [comment]
Fixed by 32c1e1a

**Comment by njsmith** [comment]
Meh, link didn't work. The commit is: https://github.com/njsmith/colorspacious/commit/32c1e1aeaa4f65967644cba2fd41d3dbc82a7558
